### ISSUE TITLE
Not all patches are getting applied

### ISSUE THREAD

**Issue by netscruff** [Unicon/grouper-dockerized#11]
When building from your Dockerfile it doesn't appear that all the patches are getting applied. First noticed in the UI since we were having problems with the UI interface under a reverse proxy even after tweaking some Tomcat server.xml setting to make it compatible for running under a reverse proxy. One of the grouper developers asked me to verify if all the patches were being applied because of the errors we were seeing and this is when I found the issue with many patches failing to apply during the build of the images.

**Comment by jtgasper3** [comment]
Hi @netscruff,

Glad to hear someone is actually using this. I actually had talks with TIER Packaging folks and shared this with them, but I wasn't sure anyone was actually using this.

Grouper's patching model is not ideal for these Docker builds. I'll take a look at build history and if anything jumps out, but can you give me a few of the failing patches so I have something to compare against?

Also, feel free to share any pull request that would benefit the community.

Thanks.

**Comment by netscruff** [comment]
Probably the wrong forum to discuss this in a github issue but I believe this must be where the TIER development is taking place.
https://github.internet2.edu/docker/grouper
You need to uncomment some lines in the onbuild file to enable the JDK download.

**Comment by jtgasper3** [comment]
Good find, but I have no idea about that project. There is also https://github.internet2.edu/docker/grouper_noVM which up until yesterday looked pretty empty. Now it looks very familiar. :D

**Comment by netscruff** [comment]
Right off the bat there is a problem appling a the first api patch:
Downloading from URL: http://software.internet2.edu/grouper/release/2.3.0/patches/grouper_v2_3_0_api_patch_0.tar.gz to file: /tmp/grp-ui/patches/grouper_v2_3_0_api_patch_0.tar.Cannot apply patch since this patch file:
  /opt/apache-tomcat-6.0.44/webapps/grouper/WEB-INF/classes/edu/internet2/middleware/grouper/util/GrouperUtil$2.class
  /tmp/grp-ui/patches/grouper_v2_3_0_api_patch_0/new/classes/edu/internet2/middleware/grouper/util/GrouperUtil$2.class
  is supposed to be new, but it already exists:
  /opt/apache-tomcat-6.0.44/webapps/grouper/WEB-INF/classes/edu/internet2/middleware/grouper/util/GrouperUtil$2.class
Problem applying patch since this file:
  /opt/apache-tomcat-6.0.44/webapps/grouper/WEB-INF/classes/edu/internet2/middleware/grouper/util/GrouperUtil$MaskingThread.class
  should not exist yet
  Do you want to force install this patch (t|f)? [f]: 
<using default which is blank due to grouperInstaller.autorun.useDefaultsAsMuchAsAvailable and grouperInstaller.autorun.forceInstallPatch>: 
Cannot apply patch since this patch file:
  /tmp/grp-ui/patches/grouper_v2_3_0_api_patch_0/new/classes/edu/internet2/middleware/grouper/util/GrouperUtil$MaskingThread.class
  is supposed to be new, but it already exists:
  /opt/apache-tomcat-6.0.44/webapps/grouper/WEB-INF/classes/edu/internet2/middleware/grouper/util/GrouperUtil$MaskingThread.class
Problem applying patch since this file:
  /opt/apache-tomcat-6.0.44/webapps/grouper/WEB-INF/classes/edu/internet2/middleware/grouper/util/GrouperUtil.class
  should not exist yet
  Do you want to force install this patch (t|f)? [f]: 
<using default which is blank due to grouperInstaller.autorun.useDefaultsAsMuchAsAvailable and grouperInstaller.autorun.forceInstallPatch>: 
Cannot apply patch since this patch file:
  /tmp/grp-ui/patches/grouper_v2_3_0_api_patch_0/new/classes/edu/internet2/middleware/grouper/util/GrouperUtil.class
  is supposed to be new, but it already exists:
  /opt/apache-tomcat-6.0.44/webapps/grouper/WEB-INF/classes/edu/internet2/middleware/grouper/util/GrouperUtil.class
Problem applying patch since this file:
  /opt/apache-tomcat-6.0.44/webapps/grouper/WEB-INF/classes/edu/internet2/middleware/grouper/util/GrouperUtil.java
  should not exist yet
  Do you want to force install this patch (t|f)? [f]: 
<using default which is blank due to grouperInstaller.autorun.useDefaultsAsMuchAsAvailable and grouperInstaller.autorun.forceInstallPatch>: 
Cannot apply patch since this patch file:
  /tmp/grp-ui/patches/grouper_v2_3_0_api_patch_0/new/classes/edu/internet2/middleware/grouper/util/GrouperUtil.java
  is supposed to be new, but it already exists:
  /opt/apache-tomcat-6.0.44/webapps/grouper/WEB-INF/classes/edu/internet2/middleware/grouper/util/GrouperUtil.java
Problem applying patch since this file:
  /opt/apache-tomcat-6.0.44/webapps/grouper/WEB-INF/classes/edu/internet2/middleware/grouper/util/GrouperUtil$DaemonThreadFactory.class
  should not exist yet
  Do you want to force install this patch (t|f)? [f]: 
<using default which is blank due to grouperInstaller.autorun.useDefaultsAsMuchAsAvailable and grouperInstaller.autorun.forceInstallPatch>: 
Cannot apply patch since this patch file:
  /tmp/grp-ui/patches/grouper_v2_3_0_api_patch_0/new/classes/edu/internet2/middleware/grouper/util/GrouperUtil$DaemonThreadFactory.class
  is supposed to be new, but it already exists:
  /opt/apache-tomcat-6.0.44/webapps/grouper/WEB-INF/classes/edu/internet2/middleware/grouper/util/GrouperUtil$DaemonThreadFactory.class
 - added to end of property file: grouper_v2_3_0_api_patch_0.state = error

**Comment by jtgasper3** [comment]
Ahh, this looks like the patching database/index file is not found so it doesn't know the API was already patched. Hopefully this is an easy fix. I'll try to get to it today or tomorrow.

Thanks.

**Comment by jtgasper3** [comment]
It looks like the `grouperPatchStatus.properties` file is not being included from the api directory when the ui (and probably ws) war(s) are being built. So the installer doesn't know that the API was previously patched.

In the Dockerfiles,  after expanding the war file, but before applying patches, the following needs to be included:

```
cp /opt/grouper.apiBinary-2.3.0/grouperPatchStatus.properties /opt/apache-tomcat-6.0.44/webapps/grouper/WEB-INF/
```

I haven't tested it yet, but I think that will do the trick. Hopefully I can get this tested and pushed this afternoon.

**Comment by jtgasper3** [comment]
I've pushed a new commit that addresses this. The patching appears to be clean now.

Thanks for point this out.
